### ISSUE TITLE
available.versions() is too conservative for packages that aren't updated frequently

### ISSUE THREAD

**Issue by gergness** [goldingn/versions#10]
This package has been awesome, thanks so much!

I noticed that I was unable to install the `survey` package using `install.versions()` because it hasn't been update since MRAN started. However, at least in this case, MRAN has the snapshot of the survey package from when MRAN started (and in fact, the same version is available today).

``` r
library(versions)
install.versions("survey", "3.30-3")
# Fails because "3.30-3" was first released before MRAN

install.dates("survey", "2014-09-18")
# Successfully installs survey package version 3.30-3
```

I'm sure there are a ton of edge cases to work out, but thought this was worth pointing out. Thanks again!

**Comment by goldingn** [comment]
Hi @gergness. I'm really sorry I didn't respond to this. Apparently I'm not getting email notifications for this repo, so only just saw this now.

Great point, should be fairly simple to fix. I'll take a look and get back to you!

**Comment by goldingn** [comment]
`versions::install.versions("survey", "3.30-3")` works fine for me now. Please let me know if you have any trouble at your end and I'll reopen the issue.

Thanks again for letting me know, and apologies once again for the delay (I'm watching the repo again now)!
